home-work-1
denys-buhlak/AltexSoft-Lab pull request #1
Opened 2021-06-01 05:41 UTC by denys-buhlak

- [] Create first version of project.

2021-06-01 11:51 UTC, Maxim-Bondar commented on hw-1/package.json
> +        "@babel/core": "*",
I wouldn't recommend to set dependencies version as `*`, because such value update major version of module, such changes can be completelly different as was before and it can brokes an appropriete work of website. In most cases such updates makes manually by developers

2021-06-01 11:52 UTC, Maxim-Bondar commented on hw-1/src/html/parts/_footer.html
> +                <p class="footer-phone">
`p` is extra wrapper here

2021-06-01 11:55 UTC, Maxim-Bondar commented on hw-1/src/html/parts/_footer.html
> +        <hr>
try to avoid such approach, you can make such line with help of css

2021-06-01 11:56 UTC, Maxim-Bondar commented on hw-1/src/html/parts/_footer.html
> +
remove wmpty line

2021-06-01 11:59 UTC, Maxim-Bondar commented on hw-1/src/html/parts/_footer.html
> +                    <svg width="30"
minify all svg with help of https://jakearchibald.github.io/svgomg/
also it is more readable if you put svg to separate image file and will use it as img href url or as background-image

2021-06-01 12:01 UTC, Maxim-Bondar commented on hw-1/src/html/parts/_header.html
> +
such separations is redundant, just separate elements inside section, starts with second element

2021-06-01 12:02 UTC, Maxim-Bondar commented on hw-1/src/html/parts/_header.html
> +            <span class="burger-line">show menu</span>
Why you put a text here?

2021-06-01 12:06 UTC, Maxim-Bondar commented on hw-1/src/html/parts/main/_faqs.html
> +            <svg xmlns="http://www.w3.org/2000/svg">
the same as comment for svg above

2021-06-01 12:08 UTC, Maxim-Bondar commented on hw-1/src/html/parts/main/_faqs.html
> +            <p class="faqs-question"
It should be a button

2021-06-01 12:08 UTC, Maxim-Bondar commented on hw-1/src/html/parts/main/_glossary.html
> +    <!-- <div class="container"> -->
remove comment

2021-06-01 12:10 UTC, Maxim-Bondar commented on hw-1/src/html/parts/main/_glossary.html
> +                <li class="glossary-list-item"
list options should have buttons inside , because when you click an item slider should change a state

2021-06-01 12:14 UTC, Maxim-Bondar commented on hw-1/src/html/parts/main/_tips.html
> +        <div class="tips__wrapper">
use consistent class naming, you didn't use underscope before

2021-06-01 12:15 UTC, Maxim-Bondar commented on hw-1/src/html/parts/main/_tips.html
> +            <div class="tip tip_close">
I would recoment to use an `article` for such blocks

2021-06-01 12:18 UTC, Maxim-Bondar commented on hw-1/src/js/parts/_faqsAccordion.js
> +    let accItem = document.getElementsByClassName('faqs-item');
those variables name are not obvious, how it matches with blocks wich was got?

2021-06-01 12:19 UTC, Maxim-Bondar commented on hw-1/src/js/parts/_faqsAccordion.js
> +export const faqsAccordion = () => {
Such method can be use in both accordions, because the main logic is the same

2021-06-01 12:21 UTC, Maxim-Bondar commented on hw-1/src/js/parts/_tipsAccordion.js
> +export const tipsAccordion = () => {
unite this method with `faqsAccordion`

2021-06-01 12:21 UTC, Maxim-Bondar commented on hw-1/src/scss/parts/_common.scss
> +    min-width: 320px;
redundant style

2021-06-01 12:22 UTC, Maxim-Bondar commented on hw-1/src/scss/parts/_common.scss
> +    min-width: 320px;
redandent style

2021-06-01 12:25 UTC, Maxim-Bondar commented on hw-1/src/scss/parts/_footer.scss
> +    &-list {
please don't use this feature, this feature is good, but in a huge projects diffferent to find such selectors in global search,
you can just declare `.list` class which will apply styles only inside this block

2021-06-01 12:25 UTC, Maxim-Bondar commented on hw-1/src/scss/parts/_footer.scss
> +        padding: 0.75em 0;
if design has strict `px` values don't use `rem` or `em`

2021-06-01 12:27 UTC, Maxim-Bondar commented on hw-1/src/scss/parts/_footer.scss
> +        // margin: 0;
remove comments

2021-06-01 12:27 UTC, Maxim-Bondar commented on hw-1/src/scss/parts/_footer.scss
> +    @media (min-width: 1024px) {
as an advice, create variables for all breakpoints and use

2021-06-01 12:28 UTC, Maxim-Bondar commented on hw-1/src/scss/parts/_footer.scss
> +hr {
don't use tag selector, create a helper class which add such line and use it where it is needed

2021-06-01 12:29 UTC, Maxim-Bondar commented on hw-1/src/scss/parts/_footer.scss
> +    height: 1.5px;
don't use float values

2021-06-01 12:30 UTC, Maxim-Bondar commented on hw-1/src/scss/parts/_footer.scss
> +    color: #b2b2b2;
if you use variables , create it for all colors

2021-06-01 12:30 UTC, Maxim-Bondar commented on hw-1/src/scss/parts/_header.scss
> +    padding: 0.5em;
use strict padding value

2021-06-01 12:31 UTC, Maxim-Bondar commented on hw-1/src/scss/parts/_header.scss
> +    &:focus {
redandent style, it wasn't mentioned in design

2021-06-01 12:35 UTC, Maxim-Bondar commented on hw-1/src/scss/parts/_header.scss
> +    width: 170px;
don't hardcode, what if content inside will be changed?

2021-06-01 12:36 UTC, Maxim-Bondar commented on hw-1/src/scss/parts/_header.scss
> +    padding: 0.6em 0;
width and height can be set by content and strict paddings (vertical and horizontal) which was mentioned in design

2021-06-01 12:36 UTC, Maxim-Bondar commented on hw-1/src/scss/parts/_header.scss
> +    &.is-small {
redundant helper

2021-06-01 12:38 UTC, Maxim-Bondar commented on hw-1/src/scss/parts/_header.scss
> +        &:last-child {
for such solution use ` & + & { margin-left: .... }` it works faster

2021-06-01 12:38 UTC, Maxim-Bondar commented on hw-1/src/scss/parts/_header.scss
> +    .logo:focus {
redundent styles

2021-06-01 12:39 UTC, Maxim-Bondar commented on hw-1/src/scss/parts/_main.scss
> +            // pointer-events: none;
remove comment

2021-06-01 12:42 UTC, Maxim-Bondar commented on hw-1/src/scss/parts/main/_glossary.scss
> +
don't separete related group styles, it is more readable

2021-06-01 12:51 UTC, Maxim-Bondar requested changes
COMMON
- active element don't have an underscore https://prnt.sc/13o4m05
- not as on the design https://prnt.sc/13o4nkh
- redundant outline https://prnt.sc/13o4om1 and don't have a cursore: poiner
- active elemenent has outline instead of side line https://prnt.sc/13o4q9b

2021-06-03 09:51 UTC, denys-buhlak commented on hw-1/package.json
> +        "@babel/core": "*",
Fixed

2021-06-06 09:48 UTC, denys-buhlak commented on hw-1/src/html/parts/_footer.html
> +                <p class="footer-phone">
Fixed

2021-06-06 09:48 UTC, denys-buhlak commented on hw-1/src/html/parts/_footer.html
> +        <hr>
Fixed

2021-06-06 09:48 UTC, denys-buhlak commented on hw-1/src/html/parts/_footer.html
> +
Fixed

2021-06-06 09:48 UTC, denys-buhlak commented on hw-1/src/html/parts/_footer.html
> +                    <svg width="30"
Fixed

2021-06-06 09:48 UTC, denys-buhlak commented on hw-1/src/html/parts/_header.html
> +
Fixed

2021-06-06 09:49 UTC, denys-buhlak commented on hw-1/src/html/parts/_header.html
> +            <span class="burger-line">show menu</span>
Validator (empty tag)

2021-06-06 09:49 UTC, denys-buhlak commented on hw-1/src/html/parts/main/_faqs.html
> +            <svg xmlns="http://www.w3.org/2000/svg">
Fixed

2021-06-06 09:49 UTC, denys-buhlak commented on hw-1/src/html/parts/main/_faqs.html
> +            <p class="faqs-question"
Fixed

2021-06-06 09:49 UTC, denys-buhlak commented on hw-1/src/html/parts/main/_glossary.html
> +    <!-- <div class="container"> -->
Fixed

2021-06-06 09:49 UTC, denys-buhlak commented on hw-1/src/html/parts/main/_tips.html
> +        <div class="tips__wrapper">
Fixed

2021-06-06 09:50 UTC, denys-buhlak commented on hw-1/src/js/parts/_faqsAccordion.js
> +    let accItem = document.getElementsByClassName('faqs-item');
Fixed

2021-06-06 09:50 UTC, denys-buhlak commented on hw-1/src/js/parts/_faqsAccordion.js
> +export const faqsAccordion = () => {
Fixed

2021-06-06 09:50 UTC, denys-buhlak commented on hw-1/src/js/parts/_tipsAccordion.js
> +export const tipsAccordion = () => {
Fixed

2021-06-06 09:51 UTC, denys-buhlak commented on hw-1/src/scss/parts/_common.scss
> +    min-width: 320px;
Fixed

2021-06-06 09:51 UTC, denys-buhlak commented on hw-1/src/scss/parts/_common.scss
> +    min-width: 320px;
Fixed

2021-06-06 09:52 UTC, denys-buhlak commented on hw-1/src/scss/parts/_footer.scss
> +    &-list {
Fixed

2021-06-06 09:52 UTC, denys-buhlak commented on hw-1/src/scss/parts/_footer.scss
> +        // margin: 0;
Fixed

2021-06-06 09:53 UTC, denys-buhlak commented on hw-1/src/scss/parts/_footer.scss
> +    @media (min-width: 1024px) {
Fixed.
Later create mixins

2021-06-06 09:53 UTC, denys-buhlak commented on hw-1/src/scss/parts/_footer.scss
> +hr {
Fixed

2021-06-06 09:53 UTC, denys-buhlak commented on hw-1/src/scss/parts/_footer.scss
> +    height: 1.5px;
Fixed

2021-06-06 09:53 UTC, denys-buhlak commented on hw-1/src/scss/parts/_footer.scss
> +    color: #b2b2b2;
Fixed

2021-06-06 09:53 UTC, denys-buhlak commented on hw-1/src/scss/parts/_header.scss
> +    padding: 0.5em;
Fixed

2021-06-06 09:54 UTC, denys-buhlak commented on hw-1/src/scss/parts/_header.scss
> +    &:focus {
Its for navigation from keyboard

2021-06-06 09:54 UTC, denys-buhlak commented on hw-1/src/scss/parts/_header.scss
> +    width: 170px;
Fixed

2021-06-06 09:54 UTC, denys-buhlak commented on hw-1/src/scss/parts/_header.scss
> +    padding: 0.6em 0;
Fixed

2021-06-06 09:54 UTC, denys-buhlak commented on hw-1/src/scss/parts/_header.scss
> +    &.is-small {
Fixed
BTW change mecanism

2021-06-06 09:55 UTC, denys-buhlak commented on hw-1/src/scss/parts/_header.scss
> +        &:last-child {
Not fixed
Remember on future

2021-06-06 09:56 UTC, denys-buhlak commented on hw-1/src/scss/parts/_header.scss
> +    .logo:focus {
Its for navigation from keyboard

2021-06-06 09:56 UTC, denys-buhlak commented on hw-1/src/scss/parts/_main.scss
> +            // pointer-events: none;
Its for navigation from keyboard

2021-06-06 09:56 UTC, denys-buhlak commented on hw-1/src/scss/parts/main/_glossary.scss
> +
Fixed
Change setting for some liners

2021-06-06 09:57 UTC, denys-buhlak commented on hw-1/src/scss/parts/_footer.scss
> +        padding: 0.75em 0;
Fixed

2021-06-06 09:57 UTC, denys-buhlak commented on hw-1/src/html/parts/main/_tips.html
> +            <div class="tip tip_close">
Not fixed
I try it later

2021-06-06 09:57 UTC, denys-buhlak commented on hw-1/src/html/parts/main/_glossary.html
> +                <li class="glossary-list-item"
Not fixed.
Want try later

2021-06-08 15:33 UTC, Maxim-Bondar commented on hw-1/src/scss/parts/_header.scss
> +// .burger {
remove comment

2021-06-08 15:35 UTC, Maxim-Bondar commented on hw-1/src/scss/parts/_header.scss
> +        &.is-current-page:focus {
`focus` can be declared below in `&.is-current-page`

2021-06-08 15:35 UTC, Maxim-Bondar commented on hw-1/src/scss/parts/_header.scss
> +        &.is-current-page:focus {
`focus` can be declared below in `&.is-current-page`

2021-06-08 15:36 UTC, Maxim-Bondar commented on hw-1/src/scss/parts/_header.scss
> +        padding-right: 57px;
write in shorthand `0 57px`

2021-06-08 18:16 UTC, denys-buhlak commented on hw-1/src/scss/parts/_header.scss
> +// .burger {
Fixed

2021-06-08 18:17 UTC, denys-buhlak commented on hw-1/src/scss/parts/_header.scss
> +        &.is-current-page:focus {
fixed

2021-06-08 18:18 UTC, denys-buhlak commented on hw-1/src/scss/parts/_header.scss
> +        &.is-current-page:focus {
fixed (duplicate previous)

2021-06-08 18:22 UTC, denys-buhlak commented on hw-1/src/scss/parts/_header.scss
> +        padding-right: 57px;
not fixed.
Early i set     padding: 7px 27px; (for class .btn)

2021-06-09 07:17 UTC, denys-buhlak commented
Fix conflict

2021-06-09 07:22 UTC, Maxim-Bondar approved these changes

2021-06-09 07:23 UTC, merged