Hw 2
denys-buhlak/AltexSoft-Lab pull request #10
Opened 2021-06-10 16:45 UTC by denys-buhlak

2021-06-12 19:57 UTC, marynakorol requested changes
needs to add sliders and change some styles

2021-06-12 19:57 UTC, marynakorol commented on hw-2/src/html/layouts/header/_banner.html
> +        <div class="banner-wrap">
text and button should be in one line on desktop
![image](https://user-images.githubusercontent.com/84564899/121787472-df00b880-cbce-11eb-8765-f25e870602ea.png)

2021-06-12 19:57 UTC, marynakorol commented on hw-2/src/scss/components/_banner.scss
> +    &-title {
title shouldn't be bold

2021-06-12 19:57 UTC, marynakorol commented on hw-2/src/html/layouts/_main.html
> +<main>
![image](https://user-images.githubusercontent.com/84564899/121787656-fdb37f00-cbcf-11eb-98c3-bce23fe58a2e.png)
buttons position is wrong

2021-06-12 19:57 UTC, marynakorol commented on hw-2/src/html/layouts/_main.html
> +    <!-- <div class="test"> <p>Lorem ipsum dolor sit amet consectetur adipisicing
tooltip missed
![image](https://user-images.githubusercontent.com/84564899/121787681-30f60e00-cbd0-11eb-8a4f-dbf2364e857e.png)

2021-06-12 19:57 UTC, marynakorol commented on hw-2/src/html/layouts/_header.html
> +        <button class="burger">
the button is enormous when clicked (during transition) remove this behavior, please
![image](https://user-images.githubusercontent.com/84564899/121787724-87fbe300-cbd0-11eb-96ab-1fcad25c5681.png)

2021-06-12 19:57 UTC, marynakorol commented on hw-2/src/scss/layouts/_footer.scss
> +.footer-social-link {
wrong position on mobile 
![image](https://user-images.githubusercontent.com/84564899/121787744-a95ccf00-cbd0-11eb-846c-2128b3d6c421.png)

2021-06-12 19:57 UTC, marynakorol commented on hw-2/src/scss/utils/_break-points.scss
> +// $breakpoints: (
useless comments

2021-06-14 13:42 UTC, denys-buhlak commented on hw-2/src/scss/utils/_break-points.scss
> +// $breakpoints: (
fixed

2021-06-16 18:47 UTC, denys-buhlak commented on hw-2/src/js/parts/_manageMenu.js
> +        if(window.innerWidth < 1024){
fixed

2021-06-16 18:47 UTC, denys-buhlak commented on hw-2/src/scss/base/_common.scss
> +    font-family: $ff--primary;
fixed

2021-06-16 18:47 UTC, denys-buhlak commented on hw-2/src/scss/components/_banner.scss
> +            font-size: 16px;
fixed

2021-06-16 18:48 UTC, denys-buhlak commented on hw-2/src/scss/base/_fonts.scss
> +// EXAMPLE (in *.scss)
fixed

2021-06-16 18:48 UTC, denys-buhlak commented on hw-2/src/js/parts/_manageMenu.js
> +            navBlock.classList.toggle('is-main-nav-visible');
fixed

2021-06-16 18:48 UTC, denys-buhlak commented on hw-2/src/html/layouts/_main.html
> +<main>
fixed

2021-06-16 18:48 UTC, denys-buhlak commented on hw-2/src/html/layouts/_main.html
> +    <!-- <div class="test"> <p>Lorem ipsum dolor sit amet consectetur adipisicing
fixed
Not sure that good way

2021-06-16 18:49 UTC, denys-buhlak commented on hw-2/src/scss/layouts/_footer.scss
> +.footer-social-link {
Not fixed.
I use another layouts (discuss by phone)

2021-06-16 18:49 UTC, denys-buhlak commented on hw-2/src/html/layouts/_header.html
> +        <button class="burger">
fixed

2021-06-16 18:50 UTC, denys-buhlak commented on hw-2/src/scss/components/_header-logo.scss
> +    // background-image: url('../../images/header-logo-light.svg');
fixed

2021-06-16 18:50 UTC, denys-buhlak commented on hw-2/src/html/layouts/header/_banner.html
> +        <div class="banner-wrap">
fixed

2021-06-16 18:58 UTC, denys-buhlak commented on hw-2/src/scss/components/_banner.scss
> +    &-title {
fixed

2021-06-16 18:58 UTC, denys-buhlak commented on hw-2/src/scss/components/_header-logo.scss
> +        width: 110px;
fixed

2021-06-16 19:00 UTC, denys-buhlak commented on hw-2/src/scss/components/_burger.scss
> +        transition: all 1s ease;
fixed

2021-06-17 12:41 UTC, marynakorol approved these changes

2021-06-17 12:41 UTC, marynakorol commented on hw-2/src/scss/layouts/footer/_social-link.scss
> +    background-size: 200%;
better to use contain prop here

2021-06-17 12:41 UTC, merged