Hw 3
denys-buhlak/AltexSoft-Lab pull request #18
Opened 2021-07-06 16:02 UTC by denys-buhlak

Create task - 3

2021-07-07 19:16 UTC, Korew requested changes
Deploy to netlify - very good, thank you :)

Please, prettify your code. It should be perfect - no unneeded empty lines, no double spaces (but in some cases you miss spaces), no trailing spaces etc. Read comments and apply changes all over the project.

 I was not able to check domino task - add inputs so I can enter my own numbers. 
 
Try to break task into several simple subtasks and write simple functions. Each function should do one action. For example for coins task you can create two functions - one will draw a line. Second function will draw whole tree (in second you will call first function as many times as many lines you have). 
 
Use only English in your code :)

2021-07-07 19:16 UTC, Korew commented on hw-3/src/domino/domino-block.css
> +.domino .TC135 {
I didn't find where class `TC135` used

2021-07-07 19:16 UTC, Korew commented on hw-3/src/style.css
> +:root {
you have 4 different css files and a lot of code repeats. It's ok to make one css for all three tasks. Or you could create one general css file + 3 other files with unique styles. On main page you link only general css, on other pages general + unique css.

2021-07-07 19:16 UTC, Korew commented on hw-3/src/domino/domino.js
> +}
I couldn't check domino task - I clicked `start` button maybe hundred times and all the time it said `Imposible. Try again!`. Please add inputs, where I can enter my own numbers

2021-07-14 20:43 UTC, denys-buhlak commented on hw-3/src/coins/coins.css
> +    width: 100%;
fix

2021-07-14 20:44 UTC, denys-buhlak commented on hw-3/src/coins/coins.css
> +
fix

2021-07-14 20:44 UTC, denys-buhlak commented on hw-3/src/atm/atm.html
> +    </head>
fix

2021-07-14 20:44 UTC, denys-buhlak commented on hw-3/src/atm/atm.js
> +    minNotes [0] = 0;
question

2021-07-14 20:44 UTC, denys-buhlak commented on hw-3/src/coins/coins.html
> +    </head>
fix

2021-07-14 20:45 UTC, denys-buhlak commented on hw-3/src/domino/domino-block.css
> +
fix
each empty line separate logic block

2021-07-14 20:45 UTC, denys-buhlak commented on hw-3/src/domino/domino-block.css
> +.domino .TC135 {
fix
Delete

2021-07-14 20:46 UTC, denys-buhlak commented on hw-3/src/style.css
> +:root {
fix

2021-07-14 20:46 UTC, denys-buhlak commented on hw-3/src/domino/domino.js
> +}
fix
Random is awesome ^)

2021-07-14 20:46 UTC, denys-buhlak commented on hw-3/src/atm/atm.html
> +                        <label for="nominal-100">100:
fix

2021-07-14 20:46 UTC, denys-buhlak commented on hw-3/src/atm/atm.js
> +    // перебираем все суммы до заданной суммы (можно начать с мин.купюры)
fix

2021-07-14 20:47 UTC, denys-buhlak commented on hw-3/src/atm/atm.js
> +        minNotes [sum] = Number.MAX_VALUE;
fix, but not sure. I correct eslint rules

2021-07-14 20:47 UTC, denys-buhlak commented on hw-3/src/atm/atm.js
> +        let curSum = sum;
fix

2021-07-14 20:48 UTC, denys-buhlak commented on hw-3/src/atm/atm.js
> +                notes[note].count -= 1;
fix

2021-07-14 20:48 UTC, denys-buhlak commented on hw-3/src/atm/atm.js
> +    const needNotes = giveMyMoney(requestSum, notes);
fix

2021-07-14 20:48 UTC, denys-buhlak commented on hw-3/src/atm/atm.js
> +        if (i == 'clone')
fix

2021-07-14 20:48 UTC, denys-buhlak commented on hw-3/src/atm/atm.js
> +    let notes=startNotes.clone();
not sure

2021-07-14 20:49 UTC, denys-buhlak commented on hw-3/src/coins/coins.js
> +        // console.log(lineForDraw);
fix

2021-07-14 20:49 UTC, denys-buhlak commented on hw-3/src/coins/coins.js
> +        quantintyItemsInit:quantintyItemsInit,
fix

2021-07-14 20:49 UTC, denys-buhlak commented on hw-3/src/coins/coins.js
> +        lineForDrawTotal:lineForDrawTotal
fix

2021-07-14 20:49 UTC, denys-buhlak commented on hw-3/src/coins/coins.js
> +    // }
fix

2021-07-14 20:49 UTC, denys-buhlak commented on hw-3/src/coins/coins.js
> +    console.clear();
fix

2021-07-14 20:50 UTC, denys-buhlak commented on hw-3/src/coins/coins.js
> +}
fix

2021-07-14 20:50 UTC, denys-buhlak commented on hw-3/src/coins/coins.js
> +    if (quantityItemsRemainder != 0) {
fix

2021-07-14 20:50 UTC, denys-buhlak commented on hw-3/src/coins/coins.js
> +    let quantityItemsRemainder=0;
fix

2021-07-14 20:50 UTC, denys-buhlak commented on hw-3/src/coins/coins.js
> +    for (let i = 1; i <=  quantityItemsRemainder  ; i++) {
fix

2021-07-14 20:51 UTC, denys-buhlak commented on hw-3/src/atm/atm.js
> +function getCash (notes,requestSum) {
fix

2021-07-15 21:23 UTC, Korew approved these changes
Great!

2021-07-15 21:23 UTC, Korew commented on hw-3/src/atm/atm.js
> +  return null;
```
  if (!cash) return null;
  
  for (const nominal of cash) {
    notes[nominal] -= 1;
  }
  return notes;
```

This is absolutely same code, but mine version 2 lines shorter :)

2021-07-15 21:23 UTC, Korew commented on hw-3/src/coins/coins.js
> +startButton.addEventListener('click', (event) => {
`'click', event => {`
if you have 1 argument - brackets not needed

2021-07-15 21:23 UTC, merged